[2022-04-30 03:07:28,509] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dataproc_bqext_bqpart_dag.bigquery_external_table_task manual__2022-04-30T02:41:16.885061+00:00 [queued]>
[2022-04-30 03:07:28,540] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dataproc_bqext_bqpart_dag.bigquery_external_table_task manual__2022-04-30T02:41:16.885061+00:00 [queued]>
[2022-04-30 03:07:28,543] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-04-30 03:07:28,553] {taskinstance.py:1239} INFO - Starting attempt 4 of 5
[2022-04-30 03:07:28,556] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-04-30 03:07:28,584] {taskinstance.py:1259} INFO - Executing <Task(BigQueryCreateExternalTableOperator): bigquery_external_table_task> on 2022-04-30 02:41:16.885061+00:00
[2022-04-30 03:07:28,624] {standard_task_runner.py:52} INFO - Started process 1319 to run task
[2022-04-30 03:07:28,669] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dataproc_bqext_bqpart_dag', 'bigquery_external_table_task', 'manual__2022-04-30T02:41:16.885061+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/dataproc_spark_dagv3.py', '--cfg-path', '/tmp/tmpyfzvn_td', '--error-file', '/tmp/tmpzj4oujyu']
[2022-04-30 03:07:28,908] {standard_task_runner.py:77} INFO - Job 9: Subtask bigquery_external_table_task
[2022-04-30 03:07:29,325] {logging_mixin.py:109} INFO - Running <TaskInstance: dataproc_bqext_bqpart_dag.bigquery_external_table_task manual__2022-04-30T02:41:16.885061+00:00 [running]> on host 2793a00d8448
[2022-04-30 03:07:29,497] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dataproc_bqext_bqpart_dag
AIRFLOW_CTX_TASK_ID=bigquery_external_table_task
AIRFLOW_CTX_EXECUTION_DATE=2022-04-30T02:41:16.885061+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-04-30T02:41:16.885061+00:00
[2022-04-30 03:07:29,505] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-04-30 03:07:30,420] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 1196, in execute
    table_resource=self.table_resource,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 430, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 408, in create_empty_table
    table=table, exists_ok=exists_ok, retry=retry
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/client.py", line 755, in create_table
    timeout=timeout,
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/client.py", line 782, in _call_api
    return call()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/retry.py", line 291, in retry_wrapped_func
    on_error=on_error,
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/retry.py", line 189, in retry_target
    return target()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/_http.py", line 484, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.BadRequest: 400 POST https://bigquery.googleapis.com/bigquery/v2/projects/quiet-rigging-347402/datasets/traffic_crashes_data/tables?prettyPrint=false: Error while reading table: final_summ_external_table, error message: Failed to expand table final_summ_external_table with file pattern gs://dtc_capstone_quiet-rigging-347402/clean.parquet: matched no files.
[2022-04-30 03:07:30,519] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=dataproc_bqext_bqpart_dag, task_id=bigquery_external_table_task, execution_date=20220430T024116, start_date=20220430T030728, end_date=20220430T030730
[2022-04-30 03:07:30,584] {standard_task_runner.py:92} ERROR - Failed to execute job 9 for task bigquery_external_table_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 1196, in execute
    table_resource=self.table_resource,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 430, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 408, in create_empty_table
    table=table, exists_ok=exists_ok, retry=retry
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/client.py", line 755, in create_table
    timeout=timeout,
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/client.py", line 782, in _call_api
    return call()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/retry.py", line 291, in retry_wrapped_func
    on_error=on_error,
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/retry.py", line 189, in retry_target
    return target()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/_http.py", line 484, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.BadRequest: 400 POST https://bigquery.googleapis.com/bigquery/v2/projects/quiet-rigging-347402/datasets/traffic_crashes_data/tables?prettyPrint=false: Error while reading table: final_summ_external_table, error message: Failed to expand table final_summ_external_table with file pattern gs://dtc_capstone_quiet-rigging-347402/clean.parquet: matched no files.
[2022-04-30 03:07:30,661] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-04-30 03:07:30,853] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
