[2022-04-25 02:28:43,420] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: gcs_2_bq_dag.bq_create_clean_crashes_summ_partitioned_table_task scheduled__2022-04-24T00:00:00+00:00 [queued]>
[2022-04-25 02:28:43,451] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: gcs_2_bq_dag.bq_create_clean_crashes_summ_partitioned_table_task scheduled__2022-04-24T00:00:00+00:00 [queued]>
[2022-04-25 02:28:43,452] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-04-25 02:28:43,454] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-04-25 02:28:43,456] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-04-25 02:28:43,494] {taskinstance.py:1259} INFO - Executing <Task(BigQueryInsertJobOperator): bq_create_clean_crashes_summ_partitioned_table_task> on 2022-04-24 00:00:00+00:00
[2022-04-25 02:28:43,515] {standard_task_runner.py:52} INFO - Started process 239 to run task
[2022-04-25 02:28:43,534] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'gcs_2_bq_dag', 'bq_create_clean_crashes_summ_partitioned_table_task', 'scheduled__2022-04-24T00:00:00+00:00', '--job-id', '183', '--raw', '--subdir', 'DAGS_FOLDER/gcs_to_bq_v1.py', '--cfg-path', '/tmp/tmp980yn21a', '--error-file', '/tmp/tmpvffjbs8p']
[2022-04-25 02:28:43,546] {standard_task_runner.py:77} INFO - Job 183: Subtask bq_create_clean_crashes_summ_partitioned_table_task
[2022-04-25 02:28:43,667] {logging_mixin.py:109} INFO - Running <TaskInstance: gcs_2_bq_dag.bq_create_clean_crashes_summ_partitioned_table_task scheduled__2022-04-24T00:00:00+00:00 [running]> on host 2c2e7134f604
[2022-04-25 02:28:43,815] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=gcs_2_bq_dag
AIRFLOW_CTX_TASK_ID=bq_create_clean_crashes_summ_partitioned_table_task
AIRFLOW_CTX_EXECUTION_DATE=2022-04-24T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-04-24T00:00:00+00:00
[2022-04-25 02:28:43,820] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-04-25 02:28:43,826] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-04-25 02:28:43,865] {bigquery.py:1637} INFO - Inserting job ***_gcs_2_bq_dag_bq_create_clean_crashes_summ_partitioned_table_task_2022_04_24T00_00_00_00_00_2d051b17881d41fd5064eabc1d997344
[2022-04-25 02:28:44,735] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2287, in execute
    job = self._submit_job(hook, job_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2253, in _submit_job
    job_id=job_id,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 430, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 1639, in insert_job
    job.result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1447, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1437, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/base.py", line 727, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/future/polling.py", line 135, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 PARTITION BY expression must be DATE(<timestamp_column>), DATE(<datetime_column>), DATETIME_TRUNC(<datetime_column>, DAY/HOUR/MONTH/YEAR), a DATE column, TIMESTAMP_TRUNC(<timestamp_column>, DAY/HOUR/MONTH/YEAR), DATE_TRUNC(<date_column>, MONTH/YEAR), or RANGE_BUCKET(<int64_column>, GENERATE_ARRAY(<int64_value>, <int64_value>[, <int64_value>]))

(job ID: airflow_gcs_2_bq_dag_bq_create_clean_crashes_summ_partitioned_table_task_2022_04_24T00_00_00_00_00_2d051b17881d41fd5064eabc1d997344)

                                                                                      -----Query Job SQL Follows-----                                                                                      

    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
   1:CREATE OR REPLACE TABLE traffic_crash_data.clean_crashes_summ             PARTITION BY DATE(CRASH_DATE)             AS             SELECT * FROM traffic_crash_data.clean_crashes_summ_external_table;
    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
[2022-04-25 02:28:44,766] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=gcs_2_bq_dag, task_id=bq_create_clean_crashes_summ_partitioned_table_task, execution_date=20220424T000000, start_date=20220425T022843, end_date=20220425T022844
[2022-04-25 02:28:44,798] {standard_task_runner.py:92} ERROR - Failed to execute job 183 for task bq_create_clean_crashes_summ_partitioned_table_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2287, in execute
    job = self._submit_job(hook, job_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2253, in _submit_job
    job_id=job_id,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 430, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 1639, in insert_job
    job.result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1447, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1437, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/base.py", line 727, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/future/polling.py", line 135, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 PARTITION BY expression must be DATE(<timestamp_column>), DATE(<datetime_column>), DATETIME_TRUNC(<datetime_column>, DAY/HOUR/MONTH/YEAR), a DATE column, TIMESTAMP_TRUNC(<timestamp_column>, DAY/HOUR/MONTH/YEAR), DATE_TRUNC(<date_column>, MONTH/YEAR), or RANGE_BUCKET(<int64_column>, GENERATE_ARRAY(<int64_value>, <int64_value>[, <int64_value>]))

(job ID: airflow_gcs_2_bq_dag_bq_create_clean_crashes_summ_partitioned_table_task_2022_04_24T00_00_00_00_00_2d051b17881d41fd5064eabc1d997344)

                                                                                      -----Query Job SQL Follows-----                                                                                      

    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
   1:CREATE OR REPLACE TABLE traffic_crash_data.clean_crashes_summ             PARTITION BY DATE(CRASH_DATE)             AS             SELECT * FROM traffic_crash_data.clean_crashes_summ_external_table;
    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
[2022-04-25 02:28:44,840] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-04-25 02:28:44,930] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
