[2022-04-24 23:48:55,020] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: local_2_gcs_2_bq_dag.format_vehicles_to_parquet_task manual__2022-04-24T22:27:24.245486+00:00 [queued]>
[2022-04-24 23:48:55,044] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: local_2_gcs_2_bq_dag.format_vehicles_to_parquet_task manual__2022-04-24T22:27:24.245486+00:00 [queued]>
[2022-04-24 23:48:55,045] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-04-24 23:48:55,046] {taskinstance.py:1239} INFO - Starting attempt 10 of 10
[2022-04-24 23:48:55,047] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-04-24 23:48:55,066] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): format_vehicles_to_parquet_task> on 2022-04-24 22:27:24.245486+00:00
[2022-04-24 23:48:55,084] {standard_task_runner.py:52} INFO - Started process 3970 to run task
[2022-04-24 23:48:55,099] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'local_2_gcs_2_bq_dag', 'format_vehicles_to_parquet_task', 'manual__2022-04-24T22:27:24.245486+00:00', '--job-id', '158', '--raw', '--subdir', 'DAGS_FOLDER/download_2_gcs_dag_V3.py', '--cfg-path', '/tmp/tmp0uneimjo', '--error-file', '/tmp/tmpxdkroqyo']
[2022-04-24 23:48:55,101] {standard_task_runner.py:77} INFO - Job 158: Subtask format_vehicles_to_parquet_task
[2022-04-24 23:48:55,225] {logging_mixin.py:109} INFO - Running <TaskInstance: local_2_gcs_2_bq_dag.format_vehicles_to_parquet_task manual__2022-04-24T22:27:24.245486+00:00 [running]> on host 2bdc5459fc64
[2022-04-24 23:48:55,350] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=local_2_gcs_2_bq_dag
AIRFLOW_CTX_TASK_ID=format_vehicles_to_parquet_task
AIRFLOW_CTX_EXECUTION_DATE=2022-04-24T22:27:24.245486+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-04-24T22:27:24.245486+00:00
[2022-04-24 23:48:59,708] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/download_2_gcs_dag_V3.py", line 30, in format_to_parquet
    table = pv.read_csv(src_file)
  File "pyarrow/_csv.pyx", line 867, in pyarrow._csv.read_csv
  File "pyarrow/_csv.pyx", line 876, in pyarrow._csv.read_csv
  File "pyarrow/error.pxi", line 143, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 99, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: CSV parse error: Expected 72 columns, got 10: 1321761,bb6994ae8c30cc51eb64c6af13110fce75a56f23d1a9ca0a6f6d6c81e9944871b6af71d7577f34cd00afea1a ...
[2022-04-24 23:48:59,797] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=local_2_gcs_2_bq_dag, task_id=format_vehicles_to_parquet_task, execution_date=20220424T222724, start_date=20220424T234855, end_date=20220424T234859
[2022-04-24 23:48:59,885] {standard_task_runner.py:92} ERROR - Failed to execute job 158 for task format_vehicles_to_parquet_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/download_2_gcs_dag_V3.py", line 30, in format_to_parquet
    table = pv.read_csv(src_file)
  File "pyarrow/_csv.pyx", line 867, in pyarrow._csv.read_csv
  File "pyarrow/_csv.pyx", line 876, in pyarrow._csv.read_csv
  File "pyarrow/error.pxi", line 143, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 99, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: CSV parse error: Expected 72 columns, got 10: 1321761,bb6994ae8c30cc51eb64c6af13110fce75a56f23d1a9ca0a6f6d6c81e9944871b6af71d7577f34cd00afea1a ...
[2022-04-24 23:49:00,234] {local_task_job.py:212} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2022-04-24 23:49:00,255] {process_utils.py:124} INFO - Sending Signals.SIGTERM to group 3970. PIDs of all processes in the group: [3970]
[2022-04-24 23:49:00,256] {process_utils.py:75} INFO - Sending the signal Signals.SIGTERM to group 3970
[2022-04-24 23:49:00,397] {process_utils.py:70} INFO - Process psutil.Process(pid=3970, status='terminated', exitcode=1, started='23:48:54') (3970) terminated with exit code 1
